# Config file for Mosquitto Broker supporting Port 1883 (Plaintext) and Port 8883 (mTLS)
per_listener_settings true

# Listener 1: Port 1883 - Plaintext (Baseline / Untrusted Network)
listener 1883
allow_anonymous true

# Listener 2: Port 8883 - Encrypted mTLS (Secure Network)
listener 8883
cafile certs/ca.crt
certfile certs/server.crt
keyfile certs/server.key
require_certificate true
use_identity_as_username true

# Access Control & Authentication
password_file configs/password.txt
acl_file configs/aclfile.txt
